arm_controller:
  follow_joint_trajectory:
    type: "ubr_controllers/FollowJointTrajectoryController"
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
  gravity_compensation:
    type: "ubr_controllers/GravityCompensation"

arm_with_torso_controller:
  follow_joint_trajectory:
    type: "ubr_controllers/FollowJointTrajectoryController"
    joints:
      - torso_lift_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint

torso_controller:
  follow_joint_trajectory:
    type: "ubr_controllers/FollowJointTrajectoryController"
    joints:
      - torso_lift_joint

head_controller:
  point_head:
    type: "ubr_controllers/PointHeadController"
  follow_joint_trajectory:
    type: "ubr_controllers/FollowJointTrajectoryController"
    joints:
      - head_pan_joint
      - head_tilt_joint

base_controller:
  type: "ubr_controllers/BaseController"

gripper_controller:
  gripper_action:
    type: "ubr1_gazebo_controllers/SimulatedGripperController"

bellows_controller:
  type: "ubr1_gazebo_controllers/SimulatedBellowsController"

gazebo:
  controllers:
    - "arm_controller/follow_joint_trajectory"
    - "arm_controller/gravity_compensation"
    - "arm_with_torso_controller/follow_joint_trajectory"
    - "base_controller"
    - "head_controller/follow_joint_trajectory"
    - "head_controller/point_head"
    - "torso_controller/follow_joint_trajectory"
    - "gripper_controller/gripper_action"
    - "bellows_controller"
  base_l_wheel_joint:
    position:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 8.0
      d: 0.0
      i: 0.5
      i_clamp: 6.0
    effort_limit: 12.0
  base_r_wheel_joint:
    position:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 8.0
      d: 0.0
      i: 0.5
      i_clamp: 6.0
    effort_limit: 12.0
  torso_lift_joint:
    position:
      p: 600.0
      d: 100.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    effort_offset: 308.0
  bellows_joint:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
  head_pan_joint:
    position:
      p: 200.0
      d: 0.0
      i: 0.5
      i_clamp: 0.1
    velocity:
      p: 0.864
      d: 0.0
      i: 0.128
      i_clamp: 0.32
  head_tilt_joint:
    position:
      p: 200.0
      d: 0.0
      i: 0.5
      i_clamp: 0.1
    velocity:
      p: 0.7668
      d: 0.0
      i: 0.1136
      i_clamp: 0.284
  shoulder_pan_joint:
    position:
      p: 100.0
      d: 10.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.1
      i: 0.0
      i_clamp: 0.0
  shoulder_lift_joint:
    position:
      p: 200.0
      d: 10.0
      i: 1.0
      i_clamp: 10.0
    velocity:
      p: 1.0
      d: 0.1
      i: 0.0
      i_clamp: 0.0
  upperarm_roll_joint:
    position:
      p: 300.0
      d: 30.0
      i: 3.49
      i_clamp: 8.725
    velocity:
      p: 0.001
      d: 0.0
      i: 0.0002
      i_clamp: 0.025
  elbow_flex_joint:
    position:
      p: 200.0
      d: 0.0
      i: 30
      i_clamp: 1.3
    velocity:
      p: 0.001
      d: 0.0
      i: 0.0002
      i_clamp: 0.025
  forearm_roll_joint:
    position:
      p: 100.0
      d: 0.0
      i: 15
      i_clamp: 0.5
    velocity:
      p: 0.001
      d: 0.0
      i: 0.0002
      i_clamp: 0.0125
    effort_limit: 3.166
  wrist_flex_joint:
    position:
      p: 30.0
      d: 3.0
      i: 1.0
      i_clamp: 0.3
    velocity:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
  wrist_roll_joint:
    position:
      p: 10.0
      d: 0.0
      i: 1.0
      i_clamp: 0.3
    velocity:
      p: 0.002
      d: 0.0
      i: 0.0002
      i_clamp: 0.2
    effort_limit: 1.0
  left_gripper_joint:
    position:
      p: 2000.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
  right_gripper_joint:
    position:
      p: 2000.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 0.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
