# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_flex_joint:
    has_velocity_limits: true
    max_velocity: 1.30899694
    has_acceleration_limits: false
    max_acceleration: 0
  forearm_roll_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951
    has_acceleration_limits: false
    max_acceleration: 0
  left_gripper_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  right_gripper_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 1.30899694
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.30899694
    has_acceleration_limits: false
    max_acceleration: 0
  torso_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  upperarm_roll_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_flex_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_roll_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951
    has_acceleration_limits: false
    max_acceleration: 0